name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on Ubuntu hosted by GitHub

    steps:
      # 1. Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment for the Flask app
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      # 4. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0  # Specify the Terraform version to use

      # 5. Initialize Terraform (set up backend, download providers)
      - name: Terraform Init
        working-directory: ./terraform  # Adjust to where your Terraform files are located
        run: terraform init -input=false

      # 6. Apply Terraform configuration to provision EC2
      - name: Terraform Apply
        working-directory: ./terraform  # Same as above
        run: |
         terraform apply \
           -auto-approve \
           -input=false \
           -var-file=ci.tfvars

      # 7. Deploy Flask app to EC2 using SSH
      - name: Deploy Flask app to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_IP }}  # EC2 IP address stored in GitHub Secrets
          username: ${{ secrets.EC2_USER }}  # EC2 username (typically 'ubuntu')
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Private SSH key stored in GitHub Secrets
          script: |
            cd /home/ubuntu/flask-devops-ci  # Navigate to the Flask project folder on EC2
            git pull origin main  # Pull the latest changes from GitHub
            pkill -f app.py || true  # Stop any previous Flask process
            nohup python3 app.py > app
