name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Job will run on Ubuntu hosted by GitHub
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the code from GitHub repo
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Set up Python 3.10 for Flask app

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install app dependencies (like Flask)

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0  # Install specific Terraform version
        
      - name: Terraform Init
        working-directory: ./terraform  # Make sure to run Terraform from the right folder
        run: terraform init  # Initialize Terraform to set up the environment

      - name: Terrform Plan
        working-directory: ./terraform
        run: terraform plan
      
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false -var-file=ci.tfvars  # Apply Terraform plan to provision EC2
        
      - name: Deploy Flask App to EC2
        uses: appleboy/ssh-action@v0.1.9  # Use SSH action to deploy the app
        with:
          host: ${{ secrets.EC2_IP }}  # EC2 IP stored in GitHub secrets
          username: ${{ secrets.EC2_USER }}  # EC2 username (usually 'ubuntu')
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored in secrets
          script: |
            cd /home/ubuntu/flask-devops-ci  # Navigate to project folder on EC2
            git pull origin main  # Pull the latest code from GitHub
            pkill -f app.py || true  # Stop any previous Flask instance if running
            nohup python3 app.py > app.log 2>&1 &  # Start the Flask app in the background
